# Generated by Django 4.2.13 on 2024-06-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disponibilite",
            old_name="enseigant",
            new_name="enseignant",
        ),
    ]
