# Generated by Django 4.1.7 on 2024-06-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_enseigant_disponibilite_enseignant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disponibilite",
            old_name="vaccation",
            new_name="vacation",
        ),
    ]
