# Generated by Django 4.1.7 on 2024-08-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_vaccation_disponibilite_vacation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disponibilite",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="disponibilite",
            name="restored_at",
        ),
    ]
