# Generated by Django 4.1.7 on 2024-06-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispenser",
            old_name="vaccation",
            new_name="vacation",
        ),
    ]
