from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from .views import *

urlpatterns = [
    path("token", TokenObtainPairView.as_view()),
    path("token/verify", TokenVerifyView.as_view()),
    path("token/refresh", TokenRefreshView.as_view()),
    path("users", UserList.as_view()),
    path("users/me", Auth.as_view()),
    path("users/create", UserCreate.as_view()),
    path("users/<int:pk>", UserDetail.as_view()),
    path("users/password/<int:pk>", UserChangePassword.as_view()),
    path("users/fonction/<int:pk>", UserChangeFunction.as_view()),
    # path("users/group/<int:pk>", UserChangeFunction.as_view()),
    path("etudiants", EtudiantList.as_view()),
    path("etudiants/create", EtudiantCreate.as_view()),
    path("etudiants/<int:pk>", EtudiantDetail.as_view()),
    path("enseignants", EnseignantCreate.as_view()),
    path("enseignants/<int:pk>", EnseignantDetail.as_view()),
    path("enseignants/disponibilites", DisponibiliteCreate.as_view()),
    path("enseignants/disponibilites/<int:pk>", DisponibiliteDetail.as_view()),
    path("promotions", PromotionCreate.as_view()),
    path("promotions/<int:pk>", PromotionDetail.as_view()),
    path("facultes", FaculteCreate.as_view()),
    path("facultes/<int:pk>", FaculteDetail.as_view()),
    path("facultaires/create", FacultaireCreate.as_view()),
    path("facultaires", FacultaireList.as_view()),
    path("facultaires/<int:pk>", FacultaireDetail.as_view()),
    path("departements", DepartementList.as_view()),
    path("departements/create", DepartementCreate.as_view()),
    path("departements/<int:pk>", DepartementDetail.as_view()),
    path("salles", SalleCreate.as_view()),
    path("salles/<int:pk>", SalleDetail.as_view()),
    path("postes", PosteList.as_view()),
    path("postes/create", PosteCreate.as_view()),
    path("postes/<int:pk>", PosteDetail.as_view()),
    path("postes/<str:slug>", PosteRetrieve.as_view()),
    path("postes/detail/<int:pk>", PosteUpdateDelete.as_view()),
    path("postes/<str:slug>/commenter", CommentaireCreate.as_view()),
    path("postes/<str:slug>/commenter/<int:pk>", CommentaireDetail.as_view()),
    path("cours", CoursCreate.as_view()),
    path("cours/<int:pk>", CoursDetail.as_view()),
    path("cours/attributions/create", AttributionCoursCreate.as_view()),
    path("cours/attributions", AttributionCoursList.as_view()),
    path("cours/attributions/now", AttributionCoursListNow.as_view()),
    path("cours/attributions/<int:pk>", AttributionCoursDetail.as_view()),
    path("cours/dispenser", DispenserCoursList.as_view()),
    path("cours/dispenser/now", DispenserCoursListNow.as_view()),
    path("cours/dispenser/create", DispenserCoursCreate.as_view()),
    path("cours/dispenser/<int:pk>", DispenserCoursDetail.as_view()),
    path("cours/horaires", Horaire.as_view()),
    path("cours/horaires/now", HoraireWeek.as_view()),
    path("annees-academiques", AnneeAcademiqueCreate.as_view()),
    path("annees-academiques/<int:pk>", AnneeAcademiqueDetail.as_view()),
]
